using Microsoft.AspNetCore.Mvc.Controllers;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;
using System.Reflection;
using System.Xml.Linq;
using System.Xml.XPath;

namespace Milvasoft.Components.OpenApi.OperationTransformers;

/// <summary>
/// Provides methods for retrieving XML documentation comments for .NET members from one or more XML documentation
/// files.
/// </summary>
/// <remarks>This service enables access to summary, remarks, and parameter descriptions for reflected members,
/// such as types, methods, and properties, by parsing standard XML documentation files generated by the C# compiler. It
/// is useful for tools that need to display or process API documentation at runtime, such as documentation generators
/// or code analyzers. The service supports multiple XML files and merges their contents, with later files overriding
/// earlier ones for duplicate member entries.</remarks>
public class XmlDocumentationService
{
    private readonly Dictionary<string, XElement> _memberElements = [];

    /// <summary>
    /// File paths to XML documentation files to load.
    /// </summary>
    /// <param name="xmlFilePaths"></param>
    public XmlDocumentationService(IEnumerable<string> xmlFilePaths)
    {
        foreach (var filePath in xmlFilePaths)
        {
            if (File.Exists(filePath))
            {
                var doc = XDocument.Load(filePath);

                foreach (var element in doc.XPathSelectElements("/doc/members/member"))
                {
                    var nameAttribute = element.Attribute("name");

                    if (nameAttribute != null && !string.IsNullOrEmpty(nameAttribute.Value))
                        _memberElements[nameAttribute.Value] = element;
                }
            }
        }
    }

    /// <summary>
    /// Gets the summary documentation for a given member.
    /// </summary>
    /// <param name="memberInfo"></param>
    /// <returns></returns>
    public string GetSummary(MemberInfo memberInfo) => GetTagValue(memberInfo, "summary");

    /// <summary>
    /// Gets the remarks documentation for a given member.
    /// </summary>
    /// <param name="memberInfo"></param>
    /// <returns></returns>
    public string GetRemarks(MemberInfo memberInfo) => GetTagValue(memberInfo, "remarks");

    /// <summary>
    /// Gets the description for a specific parameter of a method.
    /// </summary>
    /// <param name="methodInfo"></param>
    /// <param name="paramName"></param>
    /// <returns></returns>
    public string GetParamDescription(MethodInfo methodInfo, string paramName)
    {
        var element = GetMemberElement(methodInfo);

        return element?.Elements("param").FirstOrDefault(e => e.Attribute("name")?.Value == paramName)?.Value.Trim();
    }

    /// <summary>
    /// Gets the value of a specific XML tag for a given member.
    /// </summary>
    /// <param name="memberInfo"></param>
    /// <param name="tagName"></param>
    /// <returns></returns>
    private string GetTagValue(MemberInfo memberInfo, string tagName)
    {
        var element = GetMemberElement(memberInfo);

        return element?.Element(tagName)?.Value.Trim();
    }

    private XElement GetMemberElement(MemberInfo memberInfo)
    {
        var memberName = GetMemberName(memberInfo);

        return _memberElements.TryGetValue(memberName, out var element) ? element : null;
    }

    /// <summary>
    /// Generates the XML documentation member name for a given MemberInfo.
    /// </summary>
    /// <param name="member"></param>
    /// <returns></returns>
    /// <exception cref="ArgumentException"></exception>
    private static string GetMemberName(MemberInfo member)
    {
        string memberName = (member is Type type) ? type.FullName : (member.DeclaringType.FullName + "." + member.Name);

        var prefixCode = member.MemberType switch
        {
            MemberTypes.Constructor => 'M',
            MemberTypes.Method => 'M',
            MemberTypes.Event => 'E',
            MemberTypes.Field => 'F',
            MemberTypes.NestedType => 'T',
            MemberTypes.Property => 'P',
            MemberTypes.TypeInfo => 'T',
            MemberTypes.Custom => throw new ArgumentException("Unknown member type", nameof(member)),
            MemberTypes.All => throw new ArgumentException("Unknown member type", nameof(member)),
            _ => throw new ArgumentException("Unknown member type", nameof(member)),
        };

        // Retrieve method parameters for methods and constructors
        if (member is MethodInfo methodInfo)
        {
            var parameters = methodInfo.GetParameters();

            if (parameters.Length > 0)
            {
                var paramStrings = parameters.Select(p => p.ParameterType.FullName).ToArray();

                memberName += "(" + string.Join(",", paramStrings) + ")";
            }
        }

        return $"{prefixCode}:{memberName}";
    }
}

/// <summary>
/// Transforms OpenAPI operations and schemas by applying XML documentation comments from source code to generated
/// OpenAPI metadata.
/// </summary>
/// <remarks>This transformer enriches OpenAPI documentation by populating operation summaries, descriptions, and
/// parameter details, as well as schema and property descriptions, using XML comments from the codebase. It is
/// typically used to improve the quality and accuracy of generated API documentation in tools such as Swagger or
/// NSwag.</remarks>
/// <param name="xmlService">The service used to retrieve XML documentation comments for reflected members.</param>
public class XmlCommentsTransformer(XmlDocumentationService xmlService) : IOpenApiOperationTransformer, IOpenApiSchemaTransformer
{
    /// <inheritdoc/>
    public Task TransformAsync(OpenApiOperation operation, OpenApiOperationTransformerContext context, CancellationToken cancellationToken)
    {
        if (context.Description.ActionDescriptor is ControllerActionDescriptor actionDescriptor)
        {
            var methodInfo = actionDescriptor.MethodInfo;

            // Summary
            var summary = xmlService.GetSummary(methodInfo);

            if (!string.IsNullOrWhiteSpace(summary))
                operation.Summary = summary;

            // Remarks -> Description
            var remarks = xmlService.GetRemarks(methodInfo);

            if (!string.IsNullOrWhiteSpace(remarks))
                operation.Description = remarks;

            // <param name="id">
            if (operation.Parameters != null)
                foreach (var param in operation.Parameters)
                {
                    var desc = xmlService.GetParamDescription(methodInfo, param.Name);

                    if (!string.IsNullOrWhiteSpace(desc))
                        param.Description = desc;
                }
        }

        return Task.CompletedTask;
    }

    /// <inheritdoc/>
    public Task TransformAsync(OpenApiSchema schema, OpenApiSchemaTransformerContext context, CancellationToken cancellationToken)
    {
        if (context.JsonPropertyInfo != null)
        {
            if (context.JsonPropertyInfo.AttributeProvider is PropertyInfo propertyInfo)
            {
                var summary = xmlService.GetSummary(propertyInfo);

                if (!string.IsNullOrWhiteSpace(summary))
                    schema.Description = summary;
            }
        }
        else if (context.JsonTypeInfo.Type != null)
        {
            var summary = xmlService.GetSummary(context.JsonTypeInfo.Type);

            if (!string.IsNullOrWhiteSpace(summary))
                schema.Description = summary;
        }

        return Task.CompletedTask;
    }
}
