// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "member", Target = "~M:Milvasoft.UnitTests.CoreTests.HelperTests.DateTests.DateHelperTests.WithTime_WithInputTimeAndDateIsValid_ShouldReturnDateWithInputTime")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.ComponentsTests.RestTests.RequestTests.AggregationCriteriaTests")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.ComponentsTests.RestTests.RequestTests.FilterCriteriaTests")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.ComponentsTests.TypesTests.LocalizedValueTests")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.CoreTests.HelperTests.CollectionTests.CollectionHelperTests")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.CoreTests.HelperTests.DateTests.DateHelperTests")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.CoreTests.HelperTests.ExpressionTests.ExpressionHelperTests")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.CoreTests.HelperTests.PropertyTests.PropertyHelperTests")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.CoreTests.UtilTests.ConverterTests.MilvaJsonConverterOptionsTests")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.DataAccessTests.EfCoreTests.DbContextBaseTests.MilvaDbContextTests")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.DataAccessTests.EfCoreTests.MilvaEfExtensionsTests")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.PropertyTests.Core.EntityBases.DtoTests")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.PropertyTests.Core.EntityBases.EntityTests")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.PropertyTests.Core.EntityBases.TenantTests")]
[assembly: SuppressMessage("Minor Code Smell", "S2094:Classes should not be empty", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.CoreTests.HelperTests.CommonTests.Fixtures.IsAssignableToTypeModelFixtures.ClassImplementation")]
[assembly: SuppressMessage("Minor Code Smell", "S2094:Classes should not be empty", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.CoreTests.HelperTests.CommonTests.Fixtures.IsAssignableToTypeModelFixtures.ClassImplementsClassImplementation")]
[assembly: SuppressMessage("Minor Code Smell", "S2094:Classes should not be empty", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.CoreTests.HelperTests.CommonTests.Fixtures.IsAssignableToTypeModelFixtures.ClassImplementsClassImplementationWithInterface")]
[assembly: SuppressMessage("Minor Code Smell", "S2094:Classes should not be empty", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.CoreTests.HelperTests.CommonTests.Fixtures.IsAssignableToTypeModelFixtures.GenericClassImplementation`1")]
[assembly: SuppressMessage("Minor Code Smell", "S2094:Classes should not be empty", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.CoreTests.HelperTests.CommonTests.Fixtures.IsAssignableToTypeModelFixtures.GenericClassImplementsClassImplementation`1")]
[assembly: SuppressMessage("Minor Code Smell", "S2094:Classes should not be empty", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.InteceptionTests.DecoratorTests.DependencyInjectionTests.SomeDependency")]
[assembly: SuppressMessage("Minor Code Smell", "S2094:Classes should not be empty", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.InteceptionTests.DecoratorTests.DependencyLifeTimeTests.Dependency")]
[assembly: SuppressMessage("Minor Code Smell", "S2094:Classes should not be empty", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.InteceptionTests.DecoratorTests.ServiceCollectionExtensionsTests.NonDecorated1")]
[assembly: SuppressMessage("Minor Code Smell", "S2094:Classes should not be empty", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.InteceptionTests.DecoratorTests.ServiceCollectionExtensionsTests.NonDecorated2")]
[assembly: SuppressMessage("Minor Code Smell", "S2094:Classes should not be empty", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.InteceptionTests.DecoratorTests.ServiceCollectionExtensionsTests.TestChild")]
[assembly: SuppressMessage("Minor Code Smell", "S2094:Classes should not be empty", Justification = "<Pending>", Scope = "type", Target = "~T:Milvasoft.UnitTests.InteceptionTests.DecoratorTests.UnwrapTests.SomeNotDecoratedClass")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:Milvasoft.UnitTests.CoreTests.HelperTests.ExpressionTests.ExpressionHelperTests.InvalidExpressionsAndTypesForAppendMethod~System.Collections.Generic.IEnumerable{System.Object[]}")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:Milvasoft.UnitTests.CoreTests.MultiLanguageTests.MultiLanguageExtensionsTest.CreateProjectionExpression_WithMainEntityAndTranslationEntityPropertyNames_ShouldReturnCorrectExpression")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:Milvasoft.UnitTests.CoreTests.MultiLanguageTests.MultiLanguageExtensionsTest.CreateProjectionExpression_WithMainEntityPropertyNamesNullAndTranslationEntityPropertyNamesIsValid_ShouldReturnCorrectExpression")]
