name: Milvasoft.Components.CQRS Nuget Publish

on:
  push:
    branches: [ master ]
    paths:
      - 'src/Components/Milvasoft.Components.CQRS/**'
      - 'Directory.Build.props'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/Components/Milvasoft.Components.CQRS/**'
      - 'Directory.Build.props'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x
      - name: Restore Milvasoft.Components.CQRS project dependencies
        run: dotnet restore src/Components/Milvasoft.Components.CQRS/Milvasoft.Components.CQRS.csproj
      - name: Build Milvasoft.Components.CQRS project
        run: dotnet build src/Components/Milvasoft.Components.CQRS/Milvasoft.Components.CQRS.csproj --no-restore --configuration Release
      - name: Pack Milvasoft.Components.CQRS project
        run: dotnet pack src/Components/Milvasoft.Components.CQRS/Milvasoft.Components.CQRS.csproj --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o .
      - name: Publish package to NuGet
        run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
