name: Milvasoft.Attributes Nuget Publish

on:
  push:
    branches: [ master ]
    paths:
      - 'src/Components/Milvasoft.Attributes/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/Components/Milvasoft.Attributes/**'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Restore Milvasoft.Attributes project dependencies
        run: dotnet restore src/Components/Milvasoft.Attributes/Milvasoft.Attributes.csproj
      - name: Build Milvasoft.Attributes project
        run: dotnet build src/Components/Milvasoft.Attributes/Milvasoft.Attributes.csproj --no-restore --configuration Release
      - name: Pack Milvasoft.Attributes project
        run: dotnet pack src/Components/Milvasoft.Attributes/Milvasoft.Attributes.csproj --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o .
      - name: Publish package to NuGet
        run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
