name: FormFileOperations

on:
  push:
    branches: [ master ]
    paths: 
      - 'Milvasoft.FormFileOperations/**'

  pull_request:
    branches: [ master ]
    paths: 
      - 'Milvasoft.FormFileOperations/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:   
       PROJECT_FILE_PATH: Milvasoft.FormFileOperations/Milvasoft.FormFileOperations.csproj  
       NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
