name: Milvasoft.Localization.Resx Nuget Publish

on:
  push:
    branches: [ master ]
    paths:
      - 'src/Localization/Milvasoft.Localization.Resx/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/Localization/Milvasoft.Localization.Resx/**'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x
      - name: Restore Milvasoft.Localization.Resx project dependencies
        run: dotnet restore src/Localization/Milvasoft.Localization.Resx/Milvasoft.Localization.Resx.csproj
      - name: Build Milvasoft.Localization.Resx project
        run: dotnet build src/Localization/Milvasoft.Localization.Resx/Milvasoft.Localization.Resx.csproj --no-restore --configuration Release
      - name: Pack Milvasoft.Localization.Resx project
        run: dotnet pack src/Localization/Milvasoft.Localization.Resx/Milvasoft.Localization.Resx.csproj --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o .
      - name: Publish package to NuGet
        run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
