name: Milvasoft.MultiTenancy.Stores.Redis Nuget Publish

on:
  push:
    branches: [ master ]
    paths:
      - 'src/MultiTenancy/**'
      - 'Directory.Build.props'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/MultiTenancy/**'
      - 'Directory.Build.props'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x
      - name: Restore Milvasoft.MultiTenancy.Stores.Redis project dependencies
        run: dotnet restore src/MultiTenancy/Milvasoft.MultiTenancy.Stores.Redis/Milvasoft.MultiTenancy.Stores.Redis.csproj
      - name: Build Milvasoft.MultiTenancy.Stores.Redis project
        run: dotnet build src/MultiTenancy/Milvasoft.MultiTenancy.Stores.Redis/Milvasoft.MultiTenancy.Stores.Redis.csproj --no-restore --configuration Release
      - name: Pack Milvasoft.MultiTenancy.Stores.Redis project
        run: dotnet pack src/MultiTenancy/Milvasoft.MultiTenancy.Stores.Redis/Milvasoft.MultiTenancy.Stores.Redis.csproj --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o .
      - name: Publish package to NuGet
        run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
