name: Milvasoft.Storage.Abs Nuget Publish

on:
  push:
    branches: [ master ]
    paths:
      - 'src/FileOperations/**'
      - '**/Directory.Build.props'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/FileOperations/Milvasoft.Storage.Abs/**'
      - '**/Directory.Build.props'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x
      - name: Restore Milvasoft.Storage.Abs project dependencies
        run: dotnet restore src/FileOperations/Milvasoft.Storage.Abs/Milvasoft.Storage.Abs.csproj
      - name: Build Milvasoft.Storage.Abs project
        run: dotnet build src/FileOperations/Milvasoft.Storage.Abs/Milvasoft.Storage.Abs.csproj --no-restore --configuration Release
      - name: Pack Milvasoft.Storage.Abs project
        run: dotnet pack src/FileOperations/Milvasoft.Storage.Abs/Milvasoft.Storage.Abs.csproj --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o .
      - name: Publish package to NuGet
        run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
